##### JUST COPIED TO GET STARTED #####
name: test_cloud_runner
on:
  workflow_dispatch:
    inputs:
      fre-workflows-repo:
        description: "IF ON FORK: Input fre-workflows fork name (example: singhd789/fre-run-workflow). Leave empty if not using a fork."
        required: false
        type: string
      fre-workflows-branch:
        description: 'IF ON FORK: Input fre-workflows branch to check out.'
        required: false
        default: 'main'
        type: string
      fre-cli-repo:
        description: 'Input fre-cli repo (default: NOAA-GFDL/fre-cli)'
        required: true
        type: string
        default: 'NOAA-GFDL/fre-cli'
      fre-cli-branch:
        description: 'Input fre-cli branch to check out.'
        required: true
        default: 'main'
        type: string
  push:
    branches:
      - main  # triggers pipeline on push to main

jobs:
  test-cloud:
    runs-on: self-hosted
    steps:
      - name: Checkout workflow fork if specified
        if: ${{ github.event.inputs.workflow-repo != ''}}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.workflow-repo }}
          ref: ${{ github.event.inputs.workflow-branch }}
      - name: Checkout workflow repository if no fork specified
        if: ${{ github.event.inputs.workflow-repo == ''}}
        uses: actions/checkout@v4
      - name: Checkout fre-cli
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.fre-cli-repo }}
          ref: ${{ github.event.inputs.fre-cli-branch }}
          path: './fre-cli'
          submodules: true
      - name: Display fre-workflow and fre-cli repos and branches
        run: |
          # fre-run-workflow repo and branch
          echo "fre-run-workflow repo: $(git remote -v)"
          echo "fre-run-workflow branch: $(git branch)"

          # fre-cli repo and branch
          cd fre-cli
          echo "fre-cli repo: $(git remote -v)"
          echo "fre-cli branch: $(git branch)"
          cd -
      - name: Pull and run fre-cli container
        run: |
          docker pull fre-cli.sif docker://ghcr.io/noaa-gfdl/fre-cli:production
          docker images
          singularity exec --writable-tmpfs ${bind paths} fre-cli.sif ${runscript_path}
